// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import
const List<String> routeNames = <String>[
  '/',
];

class RouteName {
  const RouteName._();

  /// '/'
  ///
  /// [title] : '/'
  ///
  /// [routeName] : '/'
  ///
  /// [constructors] :
  ///
  /// RootPage : [Key? key]
  static const String root = '/';
}
